version: "3.8"
services:
  database:
    image: "mongo"
    volumes:
      - data:/data/db
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

  apiservice:
    build: ../apiservice
    volumes:
      - ../apiservice:/app
      - /app/node_modules
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on: 
      - database
      
  appservice:
    build: ../appservice
    volumes:
      - ../appservice:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
    depends_on: 
      - apiservice
volumes:
  data:


